### ISSUE TITLE
Add RTSP path in add/edit camera page

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#16]
And make "Snapshot Path" and "RTSP Path" only visible when vendor or model selected as 'Unknown/Other' (See the Android version)

**Comment by liutingdu** [comment]
@MusaabQamar 

- [ ] Change the order to be the same with Android app - 'Snapshot' should be below HTTP port, and 'RTSP URL' should be below RTSP port.
- [ ] Remove the divider in vendor & model drop down list
- [ ] RTSP path should be added to the API call creating the camera, so that I can see the RTSP path when I view camera details after adding it
- [ ] 'RTSP URL' should be added in 'Camera Details' page as well

**Comment by liutingdu** [comment]
@MusaabQamar 

I am not able to add camera because the local IP warning keep showing up. 
I'll continue testing this when   https://github.com/evercam/evercam-play-ios/issues/6 gets fixed.

**Comment by liutingdu** [comment]
@MusaabQamar 

A small thing: RTSP URL in 'Camera Details' page should be the RTSP extension, not full URL starts with 'RTSP://', it should be same format with Snapshot

**Comment by MusaabQamar** [comment]
‘Fixed, please test’
