### ISSUE TITLE
New vendor & model layout in add/edit camera page

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#21]
In the new layout it moves vendor and model info to the top of the page and added image views for vendor & model logo & thumbnail (See the Android app and the screenshot)

![screenshot sep 23 2015 15-09-34](https://cloud.githubusercontent.com/assets/5046761/10047258/398cbf9a-6205-11e5-96d5-a98f01732beb.png)

Make "Unknown/Other" to be selected by default.

**Comment by liutingdu** [comment]
@MusaabQamar 

- [ ] When I select a vendor from the vendor list, it always freezes the app at loading the image for 'Default' model
- [ ] Reduce the space below vendor/model

**Comment by liutingdu** [comment]
@MusaabQamar 

- [ ]  The app still freezes when I select a vendor from the vendor list (Please test it by select vendor 'Axis Communications')
- [ ] When I select a vendor, Evercam ID always shows up and overlay with camera Name
- [ ] In Edit Camera page, if the camera already has vendor id and model id, the model & vendor in dropdown list is automatically selected. Which means the vendor logo and model thumbnail should be automatically selected too

Please let me know if you have any problem with this.

**Comment by liutingdu** [comment]
@MusaabQamar  @ahmadhassanch 

Thanks for resolving bugs that already exists and are not in contract list :) Would be great if you can let me know what they are, we can create new issue for them and leave them to the next version.

I think this one needs more work:
- [ ] The app still freezes when I select a vendor from the vendor list (Can be reproduced by selecting vendor 'Axis Communications' or 'Hikvision')
- [ ] The vendor image is scaled incorrectly, it should keep the image's original ratio, For example, see the screenshot attached, which shows the difference between iOS and Android
- [ ] Make vendor logo image view smaller
- [ ] The vendor logo should be on top of model thumbnail (you can see it from the screenshot that the model thumbnail with a white background is on top of the vendor logo)

![screen shot 2015-12-03 at 10 47 19](https://cloud.githubusercontent.com/assets/5046761/11558549/45f90a12-99ab-11e5-8f05-829674f1c5b4.png)

<img width="372" alt="screen shot 2015-12-03 at 10 49 15" src="https://cloud.githubusercontent.com/assets/5046761/11558613/8af338b8-99ab-11e5-87be-ac60607398a8.png">

**Comment by MusaabQamar** [comment]
‘Fixed, please test’
