### ISSUE TITLE
Improve user interface

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#22]
Make the user interface to be similar with the Android app in colors, layouts. But it should follow iOS UI guidance instead of just copy everything from Android.

1. Improve the slide menu: 
 - Remove the divider
 - Increase spacing between the icon and text
 - Change background color to be white (icon color ```#696969```, text color ```#333333```)
 - Add same dark title with background ```#34393d``` (same with Android) and add Evercam logo, version number(color ```#696969```) and the current user's Email and name to the title
 - Add item 'About Evercam'
 - Remove the 'About' section in settings page because not it belongs to the slide menu

2. Replace the icons in 'Account' page 

3. Improve the dropdown lists (Replace the old Android style icon, remove the divider)

4. Remove the red divider for dialog (Account - Add new account)

**Comment by liutingdu** [comment]
@MusaabQamar 

Slide menu:
- [ ] Make 'Sign Out' to be the last one
- [ ] The white background should fill page height
- [ ] The slide menu should be able to scroll (You can see it when the phone is rotated)
- [ ] The text color for the menu items should be ```#333333``` (Currently it's a very light grey)
- [ ] Make the evercam.io logo smaller so that the version number fits in the same line
- [ ] Make the texts and icons smaller for the menu items

Other:
- [ ] Remove title 'GENERAL' from settings, because 'About' section has been removed and there is no reason to keep it
- [ ] Icons in account page should be white
- [ ] Remove divider from the drop down list

**Comment by liutingdu** [comment]
@MusaabQamar 

- [ ] The 'Name' label should show user's full name(first name + last name), not username
- [ ] The app version text should show the current app version, instead of hard coding 'v1.0.3'

**Comment by MusaabQamar** [comment]
‘Fixed, please test’

**Comment by liutingdu** [comment]
@MusaabQamar I've tested it closed it. :)  Please only check those issues are still open
