### ISSUE TITLE
The text fields in sign up page doesn't show flashing cursor when focused

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#29]
Other page should be tested as well

**Comment by Zulqarnain-Mustafa** [comment]
This issue only appear on Simulator, working perfectly alright on device.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa 

I'm able to reproduce it on iPhone 6s. What device are you testing on? I'll share my screen with you if it helps :)

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu  iPhone 4 and cursor is there when you tap on textfield and flashing.

**Comment by Zulqarnain-Mustafa** [comment]
Issue Fixed.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa Did you forget to send a pull request?

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa The flashing cursor is still not showing up on my phone. Could you have a look at this again?

**Comment by liutingdu** [comment]
:+1:
