### ISSUE TITLE
Integrate Intercom

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#34]
https://github.com/intercom/intercom-ios

Identify the user when they signed in or opened the app with their username. 

Clear the identification when user signed out.

**Comment by Zulqarnain-Mustafa** [comment]
Integrate intercom and test it.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa I see you added lots of Intercom.framework source files to our repository, why you use Intercom.framework instead of using Cocoapods?

**Comment by Zulqarnain-Mustafa** [comment]
I added the intercom with Cocoapods, but it was giving me some thing like "Message UI" images are missing, so i have to add it manually.

**Comment by Zulqarnain-Mustafa** [comment]
I was facing this issue @liutingdu  https://github.com/intercom/intercom-ios/issues/94
