### ISSUE TITLE
Use Intercom for feedback

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#41]
See 'Live Support' in the Android app (Sendgrid should be removed)

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa That's fast! 👍 

There are remaining issues:
- Sendgrid should be removed completely (Now it still exists in ```FeedBackViewController.m```), all code related to the old feedback should be removed too
- Did you enable push notifications so that the user can receive our message when they are not using the app?

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu  i am not using `FeedBackViewController.m ` anywhere, Now FeedBackViewController is not loading from anywhere.
No i did not enable the push Notification for intercom yet.

**Comment by liutingdu** [comment]
I mean, if the code is not used anywhere, then we should remove it :) 

I've reopened this issue for adding notification & code cleaning!
