### ISSUE TITLE
Use WebSocket for JPG live view

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#42]
For JPG cameras, the way we do live view is replace the snapshot image per second in an image view by requesting live snapshot endpoint repeatly. 

This should be replaced by using WebSocket. We've done it on server side and in the Android app. It opens a connection and let the server push JPG contents, instead of asking for them.

Here is the code for Android: https://github.com/evercam/evercam-play-android/blob/master/evercamPlay/src/main/java/io/evercam/androidapp/tasks/LiveViewRunnable.java#L60-L130

In iOS, it should use Phoenix Swift / Objective-C client.

**Comment by marcoherbst** [comment]
@mosic  any tips here? Can we use https://github.com/davidstump/SwiftPhoenixClient

@MusaabQamar ? can we include SWIFT code?

**Comment by mosic** [comment]
Yep, that seems like the way to go. There's also Objective-C version but it seems less active: https://github.com/RokkinCat/phoenix-objc

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu  @marcoherbst  @mosic  the above mentioned phoenix client does not work for me so i use this on: https://github.com/livehelpnow/ObjCPhoenixClient

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa 👍 Thanks!
