### ISSUE TITLE
Crash NSInvalidArgumentException with 'containsString' on iOS 7

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#44]
This crash is happening at multiple places, for example: 
```
0x52963 -[SignupViewController onCreateAccount:] (SignupViewController.m:184)
```
and 
```
0x1000dee98 -[LoginViewController onLogin:] (LoginViewController.m:100)
```
and should be more.

We have 10% users on iOS 7.

**Comment by Zulqarnain-Mustafa** [comment]
Issue Fixed.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa

When I search for 'containsString' in the whole project, it's still showing many results. They all might need to be resolved in order to fix this issue, otherwise, it will keep crashing. 

Let me know if there is a reason not to fix them all :)

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu  Please pull the latest code, problem is solved.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa How about line 156 in ```AccountsViewController.m```?

```else if ([username containsString:@" "])```

I think you've replacd the pop up dialog for adding account with the login page, would you remove all related verbose code? (including the dialog, the add account logic code etc.) By doing that, the remaining containsString should be resolved as well.
