### ISSUE TITLE
Use new thumbnail endpoint

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-play-ios#46]
Camera thumbnail is used at two places: 1. The image in main camera list and 2. The placeholder image in live view.

Currently we get the value from 'thumbnail_url' in camera object. It should be replaced with the new thumbnail endpoint: 

https://media.evercam.io/v1/cameras/gpocam/thumbnail?api_id=api_id&api_key=api_key

The code for new API endpoint should be implemented in the objc wrapper: https://github.com/evercam/evercam-objc

Equivalent issue in Android: https://github.com/evercam/evercam-play-android/issues/149

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu on Home screen where All cameras list shows, I am receiving all cameras status to Online, so how do you show a camera Offline while the camera status is Online. I have sent you screen shots please check mail. I have implemented this end point but now camera online offline status is confusing.

**Comment by liutingdu** [comment]
We've confirmed that it's a bug in the API: https://github.com/evercam/evercam-api/issues/622

**Comment by liutingdu** [comment]
Now the thumbnail URL endpoint is implemented in the app (for the convenient of testing within the app without releasing the wrapper too frequently)

Later we are going to move it to the wrapper, the old ```thumbnial_url``` attribute should be removed from the wrapper as well. https://github.com/evercam/evercam-play-ios/issues/63
