### ISSUE TITLE
Incorrect screen rotate

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#52]
Reproduce:

1. Open the main page
2. Rotate the phone to landscape
3. Open menu, click 'Accounts'

Then the accounts page is opened as portrait screen. It should be opened as landscape. 

The same problem should be fixed for all pages, including Settings, Feedback, Add Camera and so on. 

All pages should be tested before publishing the next version.

**Comment by liutingdu** [comment]
Now the pages can be opened as landscape but with strange layout (see screnshots), releasing like this is even worse than not supporting landscape. @Zulqarnain-Mustafa Can you fix them in this milestone?  (Let me know if it's a big job then we'll roll it back, release a stable version and then fix it later.)

![2 pic](https://cloud.githubusercontent.com/assets/5046761/14355932/b4e9e80a-fcda-11e5-9828-1b15b587d9a3.jpg)
![3 pic](https://cloud.githubusercontent.com/assets/5046761/14355930/b4e9c208-fcda-11e5-8598-15109da87498.jpg)
![4 pic](https://cloud.githubusercontent.com/assets/5046761/14355931/b4e9b858-fcda-11e5-939d-d32d2055765f.jpg)
![5 pic](https://cloud.githubusercontent.com/assets/5046761/14355933/b4ee8572-fcda-11e5-8f0c-c5fe3028fe54.jpg)

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu  this is what i told you, Ok i will fix the screens.
