### ISSUE TITLE
Incorrect screen rotate on Add Camera Screen

### ISSUE THREAD

**Issue by hunainfromfsd** [evercam/evercam-play-ios#54]
When i login in app and move iPhone into Lanscape and press "+" button to add camera then screen again appears to portrait

**Comment by liutingdu** [comment]
@hunainfromfsd 

Thanks for reporting, it's a critical issue and possibly duplicate with https://github.com/evercam/evercam-play-ios/issues/52. I'll close this and continue tracking on that one.
