### ISSUE TITLE
">" icon from setting screen should be removed

### ISSUE THREAD

**Issue by hunainfromfsd** [evercam/evercam-play-ios#56]
Setting screen top 2 cells have icon ">" which means on tap the cell will push to new screen (default behaviour of iPhone UI), but if we show list action sheet on tap then ">" icon should remove

**Comment by liutingdu** [comment]
@hunainfromfsd Thanks, this is useful information :+1: 

Since we want to keep the selection dialog instead of showing new pages, the task is to remove '>' icons from setting page.
