### ISSUE TITLE
Back Button on Feedback not working

### ISSUE THREAD

**Issue by hunainfromfsd** [evercam/evercam-play-ios#57]
Reproduce:
1. Run App -> Setting -> Turn On "Force landscape for live view"
2. Tap any live camera on live view list -> screen appears in landscape mode
3. Press Top menu on right side and select "Send Feedback"

After all above steps you cant come back, the back button is not working

**Comment by liutingdu** [comment]
@hunainfromfsd Nice catch :+1:
