### ISSUE TITLE
Add Camera: Warn the user if they typed in a private/local IP address

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#6]
This is done in the Android app

Use regular expression:

Java: (127.0.0.1)|(192.168.*$)|(172.1[6-9].*$)|(172.2[0-9].*$)|(172.3[0-1].*$)|(10.*$)

**Comment by liutingdu** [comment]
Reopen this because there is a bug.

@ahmadhassanch 

To reproduce: 

1. In add camera page, type in a local IP address(192.168.1.1)
2. Click the return button, and choose 'Yes' in the confirm dialog

Then the local IP warning dialog always show up twice. It shouldn't.

**Comment by liutingdu** [comment]
Hi @MusaabQamar,

The bug is fixed but I think it brought a new bug, to reproduce:

1. Open add camera page 
2. Click on the IP address text field, then click on any other input text field 

It seems the warning dialog always shows up no matter it's a local IP address or not

**Comment by MusaabQamar** [comment]
Needs more discussion (on our side it is ok, can't reproduce)

**Comment by MusaabQamar** [comment]
‘Fixed, please test’
