### ISSUE TITLE
Changes to be made in the Objective-C wrapper

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#63]
- [x] Move code of thumbnail URL endpoint to the wrapper
- [x] Remove the old ```thumbnial_url``` attribute
- [x] Test snapshot

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  there is no need to move that in Objective-c wrapper "Move code of thumbnail URL endpoint to the wrapper".

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  i will check that `thumbnial_url ` i am not clear whether we are using it or not, after checking that i will remove that or leave it as it is.
