### ISSUE TITLE
Understand why it shows "Camera Offline" in live view

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#64]
After creating a camera with an incorrect password, the API indicates the camera is online but the app is showing offline. 

We need to understand how it works in the app and try to make iOS and Android consistent.

**Comment by Zulqarnain-Mustafa** [comment]
In code the camera status is setting manually. Please check class "AddCameraViewController.m" at line 403 `                                                                              [self createCamera:cameraBuilder withStatus:NO];`
@liutingdu  So please guide me what to do next?

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa 

Thanks for explaining :)

So in the iOS app, if the auto snapshot test failed to retrieve a snapshot from the camera, it will create the camera with ```is_online=false```, that was a nice solution! (I thought I [forced it to be online](https://github.com/evercam/evercam-play-ios/blob/master/evercamPlay/Controllers/AddCameraViewController.m#L854), but it actually gets overwritten by [this line](https://github.com/evercam/evercam-play-ios/blob/master/evercamPlay/Controllers/AddCameraViewController.m#L861)

Am I understanding it correctly?

For now I think we can leave it (because it works as we expected and we understand the logic behind it) but keep it in mind so that you can easily make improvements later.
