### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#66]
The dependencies in ```Podfile.lock``` should be upgraded regularly to get the lastest features from those third party libraries.

I've added the project to the [dependency version check tool](https://www.versioneye.com/user/projects/5703cbe7fcd19a0039f15c6b?child=summary#tab-dependencies) and added the bedge at the very top of the [README](https://github.com/evercam/evercam-play-ios/blob/master/README.md) file.

Upgrading can be dangerous, so make sure to fully test the app after doing this.

[SplunkMint.framework](https://github.com/evercam/evercam-play-ios/tree/master/SplunkMint.framework) should be removed, we've replaced it with Crashlytics.

**Comment by Zulqarnain-Mustafa** [comment]
Dependencies are updated as you can see screen shot of my terminal:
![screen shot 2016-04-11 at 4 01 27 pm](https://cloud.githubusercontent.com/assets/8174314/14426570/58466f56-0009-11e6-926c-a59824d3fe6b.png)
