### ISSUE TITLE
In LoginViewController there is no handling on Screen Rotation.

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-play-ios#69]
when we load the login screen from Account page in landscape mode, the login screen view does set to support landscape mode.

**Comment by liutingdu** [comment]
Seems this is fixed already? @Zulqarnain-Mustafa

**Comment by Zulqarnain-Mustafa** [comment]
@liutingdu This is fixed with screen rotation issue.
