### ISSUE TITLE
Use the media offline image

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#76]
Issue for Android: https://github.com/evercam/evercam-play-android/issues/166

Screenshot:
<img width="350px "src="https://cloud.githubusercontent.com/assets/5046761/14461689/906235a2-00bb-11e6-9186-06e4fed51f31.png">

**Comment by ahmadhassanch** [comment]
Hi Liuting,

   Can you kindly remove me from the list of developers.


Kind Regards,

Ahmad


________________________________

**Comment by liutingdu** [comment]
Hi @ahmadhassanch, just did. Sorry about this.
