### ISSUE TITLE
It shouldn't show the thumbnail when replay from pause

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-ios#8]
This is for JPG camera that doesn't have a valid RTSP URL.

It shows thumbnail of the camera first, then replace it with live JPG images. When user click the pause button, then hit play to reload live images, it always shows the thumbnail again. It shouldn't show the thumbnail when replay from pause.

**Comment by liutingdu** [comment]
Couldn't test this because JPG view doesn't work at all.. It always showing a black screen(To reproduce this, just play the demo camera 'Evercam Demo Wicklow', screenshot attached)

![screen shot 2015-11-18 at 15 43 12](https://cloud.githubusercontent.com/assets/5046761/11245528/1b3b80e4-8e0b-11e5-9536-66a9d6b5e19c.png)

**Comment by liutingdu** [comment]
@MusaabQamar 

You've made the change of "don't show the thumbnail when replay from pause", but now it always shows black screen when replay from pause, or even when starts a fresh play. What we really want is, it should show the thumbnail when a new play starts, and when user hit pause button and replay it, the loading animation shows up on the current image, and the image & loading animation will soon be replaced with the new arrived image.

Please feel free to ask me if it confuses you, and I think it would be helpful to check how the Android app works.

**Comment by MusaabQamar** [comment]
‘Fixed, please test’
